version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: matbank-db
    restart: always
    environment:
      POSTGRES_USER: matbank_user
      POSTGRES_PASSWORD: matbank_password
      POSTGRES_DB: matbank_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: