spring.application.name=MatBank

# 1. Po??czenie z Dockerem (musi pasowa? do docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/matbank_db
spring.datasource.username=matbank_user
spring.datasource.password=matbank_password
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate (To sprawi, ?e Java sama stworzy tabele!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect